//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iPhoneBook.rc
//

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_IPHONEBOOK_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_IPHONEBOOK			107
#define IDI_SMALL				108
#define IDC_IPHONEBOOK			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1

#define IDB_ON                     202
#define IDB_OFF                    203

#define	IDB_IFONE_BG					210			
#define	IDB_TOP_BAR_SKYPE_OFF			211
#define	IDB_TOP_BAR_SKYPE_ON			212
#define	IDB_MAIN_WND_UNDER_DATE_BG		213
#define	IDB_MAIN_WND_CENTER_PIC			214
#define	IDB_MAIN_WND_LOW_BAR_LEFT		215
#define	IDB_MAIN_WND_CLOCK_OFF			216
#define	IDB_MAIN_WND_CLOCK_ON			217
#define	IDB_MAIN_WND_CONTACT_OFF		218
#define	IDB_MAIN_WND_CONTACT_ON			219
#define	IDB_MAIN_WND_INFO_OFF			220
#define	IDB_MAIN_WND_INFO_ON			221
#define	IDB_MAIN_WND_BIN_FULL_OFF		222
#define	IDB_MAIN_WND_BIN_FULL_ON		223
#define	IDB_MAIN_WND_BIN_EMPTY_OFF		224
#define	IDB_MAIN_WND_BIN_EMPTY_ON		225
#define	IDB_MAIN_WND_LOW_BAR_RIGHT		226
#define	IDB_CONTACT_WND_APP_NAME		227
#define	IDB_CONTACT_WND_SEARCH			228
#define	IDB_CONTACT_WND_LET_SEP			229
#define	IDB_CONTACT_WND_NAME_BG_OFF		230
#define	IDB_CONTACT_WND_NAME_BG_ON		231
#define	IDB_CONTACT_WND_BUTTON_BG		232
#define	IDB_CONTACT_WND_BUTTON_CALL_OFF	233
#define	IDB_CONTACT_WND_BUTTON_CALL_ON	234
#define	IDB_CONTACT_WND_BUTTON_INFO_OFF	235
#define IDB_CONTACT_WND_BUTTON_INFO_ON	236
#define IDB_CONTACT_WND_BUTTON_EDIT_OFF	237
#define IDB_CONTACT_WND_BUTTON_EDIT_ON	238
#define	IDB_CONTACT_WND_BUTTON_DEL_OFF	239
#define	IDB_CONTACT_WND_BUTTON_DEL_ON	240
#define	IDB_EXIT_BUTTON_OFF				241
#define	IDB_EXIT_BUTTON_ON				242


#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
